import type { Metadata } from 'next';
import './globals.css';
import { Flowbite, ThemeModeScript } from 'flowbite-react';

export const metadata: Metadata = {
  title: 'CineTracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`antialiased bg-white dark:bg-black`}>
        <Flowbite>{children}</Flowbite>
      </body>
    </html>
  );
}
